### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by jobsamuel** [JinJunho/Madeleine.js#2]
Hi Jin! 
Hey, It might be awesome to add a built in drag and drop funtionality to Madeleine.js :smiley:

Regards!

**Comment by gossterrible** [comment]
Hi @JinJunho
I was think if it was possible to integrate a .obj file loader to the project this will be great,I am currently using Madeleine.js for my project and i find it very easy and efficient
Best Regards.
Boniface.

**Comment by victorazevedo** [comment]
Improved the plugin with drag and drop and with another features check in:

https://github.com/JinJunho/Madeleine.js/pull/5/commits

**Comment by JinJunho** [comment]
Thank you @victorazevedo, just merged your commit and this issue is resolved :)
